enable:
  issues: false
  prs: true

labels:
  'bug':
    include:
      - '\bbug\b'
      - '\bfix\b'
  'build':
    include:
      - '\bbuild\b'
  'doc':
    include:
      - '\bdocs\b'
  'feature':
    include:
      - '\bfeat\b'
  'refactor':
    include:
      - '\brefactor\b'
  'test':
    include:
      - '\btest\b'
  'performance':
    include:
    - '\bperformance\b'