name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-changes:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Added files
        id: files
        uses: dorny/paths-filter@v3
        with:
          filters: |
            added:
              - added: 'db/migrations/**/*.sql'
            modified:
              - modified: 'db/migrations/**/*.sql'
            deleted:
              - deleted: 'db/migrations/**/*.sql'

      - name: Add label for added files
        if: steps.files.outputs.added == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: db-migration-added

      - name: Add label for modified files
        if: steps.files.outputs.modified == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: db-migration-modified

      - name: Add label for deleted files
        if: steps.files.outputs.deleted == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: db-migration-deleted

#      - name: Label added files
#        if: steps.files.outputs.added == 'true'
#        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "db-migration-added"
#
#      - name: Label modified files
#        if: steps.files.outputs.modified == 'true'
#        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "db-migration-modified"
#
#      - name: Label deleted files
#        if: steps.files.outputs.deleted == 'true'
#        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "db-migration-deleted"



  conventional-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run label CI
        uses: AntonioGally/ag-pr-labeler/@main
        with:
          createRepoLabels: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}