name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-changes:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Added files
        id: files
        uses: dorny/paths-filter@v3
        with:
          filters: |
            added:
              - added: 'db/migrations/**/*.sql'
            modified:
              - modified: 'db/migrations/**/*.sql'
            deleted:
              - deleted: 'db/migrations/**/*.sql'

      - name: Label added files
        if: steps.files.outputs.added == 'true'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "db-migration-added"

      - name: Label modified files
        if: steps.files.outputs.modified == 'true'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "db-migration-modified"

      - name: Label deleted files
        if: steps.files.outputs.deleted == 'true'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "db-migration-deleted"

  auto-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Labeler
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}